version: "3.9"

services:
  server:
    build:
      context: ./
      dockerfile: DockerfileServer
    ports:
      - "9993:9993"
  client:
    build:
      context: ./
      dockerfile: DockerfileClient
